version: 1
services:
  - type: web
    name: jeevanti-service  # Give a meaningful name
    env: python
    buildCommand: pip install -r requirements.txt  # Ensure your requirements.txt file is in the root directory
    startCommand: python app.py  # Correct path to your Flask app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
