version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app.app:app --bind 0.0.0.0:5000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
