version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    gunicorn flask_app.app:app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
